name: Test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  unitTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.5

      - run: npm ci
      - run: npm run ci
